### ISSUE TITLE
A tiny clarification

### ISSUE THREAD

**Issue by src4026** [CTF-handbooks/map-maker-handbook#2]
So based on the last line of the handbook at present, you are planning for making a WE command handbook? How would linking to the one on GitHub be? https://github.com/Uberi/Minetest-WorldEdit/blob/master/ChatCommands.md

**Comment by src4026** [comment]
~~Feels good adding labels for the first time ever :laughing:~~

**Comment by a-blob** [comment]
One of the major reasons I'm making the handbook, or in other words rewriting the CTF map readme, is because of the confusion people have with world edit. Many of the trees and a small part of the terrain in Lost Mountain used to be cut in half by the red build time barrier, probably caused by bad WorldEdit usage.
The WorldEdit handbook will be dedicated on how to place boarders for a CTF map. The handbook should be part of the map maker handbook, but I don't want it to be too bloated so the WorldEdit handbook will be a seperated .md file in the map maker handbook repository.

**Comment by a-blob** [comment]
I find https://github.com/Uberi/Minetest-WorldEdit/blob/master/ChatCommands.md confusing and time consuming. The handbook should simplify the process.

**Comment by src4026** [comment]
:thumbsup:
